version: '3'
services:
#  api:
#      build: .
#      environment:
#        - ENVNAME=dev
#      ports:
#        - 8080:8080
#      depends_on:
#        - db_primary
#        - db_second
#        - db_third
#        - redis
#      command:
#        - "./startup.sh" # TODO: change here to enable devtools

  db_primary:
    image: mongo:3.4
    restart: always
    ports:
      - 27018:27017
    volumes:
      - "./db/data:/data/db"
      - "./db/conf:/data/conf"
    command:
      - "mongod --config /data/conf/mongo.conf"
      #- "--auth"

#  db_second:
#      image: mongo:3.4
#      restart: always
#      ports:
#        - 27019:27017
#      volumes:
#       - "./db/conf:/data/conf"
#      command:
#        - "mongod --config /data/conf/mongo.conf"
#        #- "--auth"
#
#  db_third:
#      image: mongo:3.4
#      restart: always
#      ports:
#        - 27020:27017
#      volumes:
#        - "./db/conf:/data/conf"
#      command:
#        - "mongod --config /data/conf/mongo.conf"
#        #- "--auth"
#
#  redis:
#    image: redis:alpine
#    restart: always
#    ports:
#      - 6379:6379
